- name: Set hostname agent sandbox
  hostname:
    name: "{{ hostname }}"

- name: Install fontconfig
  ansible.builtin.apt:
    name: fontconfig
    state: present

- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present

- name: Display Java version
  ansible.builtin.shell:
    cmd: "java -version"
  register: java_version_output

- name: Print Java version
  ansible.builtin.debug:
    var: java_version_output.stdout_lines

- name: Generate SSH key pair agent sandbox
  ansible.builtin.openssh_keypair:
    path: "/home/titan/.ssh/id_rsa_sandbox"
    type: rsa
    size: 2048
    state: present
  register: ssh_key_result

- name: Display public key agent sandbox
  ansible.builtin.debug:
    var: ssh_key_result

- name: Send Discord Notification on Success
  command: >
    curl -X POST
    -H "Content-Type: application/json"
    -d '{"content": "Ansible Playbook Agent Sandbox Execution Successful!"}'
    "{{ discord_webhook }}"
  ignore_errors: true
  when: ssh_key_result.type == "rsa"

- name: Send Discord Notification on Failure
  command: >
    curl -X POST
    -H "Content-Type: application/json"
    -d '{"content": "Ansible Playbook Agent Sandbox Execution Failed!\nError Message: {{ ansible_job_result.msg }}" }'
    "{{ discord_webhook }}"
  ignore_errors: true
  when: ssh_key_result.type != "rsa"
