- name: Linux Update
  hosts: 
    - awx-server
    - jenkins-server
    - agent-jenkins-sandbox-server
    - agent-jenkins-fire-server
    - atlantis-server
    - mariadb-prod-server
    - mariadb-stag-server
  become: true
  roles:
    - linux
