- name: Setup mariadb server staging
  hosts: mariadb-stag-server
  become: true
  vars: 
    - hostname: mariadb-stag-server
  vars_files:
    - mariadb_stag_secret.yaml
  roles:
    - linux
    - mariadb-stag-server
