- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Install fontconfig
  ansible.builtin.apt:
    name: fontconfig
    state: present

- name: Install OpenJDK 11
  ansible.builtin.apt:
    name: openjdk-11-jdk
    state: present