- name: Set hostname agent fire
  hostname:
    name: "{{ hostname }}"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  notify:
    - Update apt cache

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Set permissions for /var/run/docker.sock
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: '0666'

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Restart Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
  notify:
    - Update apt cache
    
- name: Install fontconfig
  ansible.builtin.apt:
    name: fontconfig
    state: present

- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present

- name: Display Java version
  ansible.builtin.shell:
    cmd: "java -version"
  register: java_version_output

- name: Print Java version
  ansible.builtin.debug:
    var: java_version_output.stdout_lines

- name: Generate SSH key pair agent fire
  ansible.builtin.openssh_keypair:
    path: "/home/titan/.ssh/id_rsa_fire"
    type: rsa
    size: 2048
    state: present
  register: ssh_key_result

- name: Display public key agent fire
  ansible.builtin.debug:
    var: ssh_key_result

- name: Send Discord Notification on Success
  command: >
    curl -X POST
    -H "Content-Type: application/json"
    -d '{"content": "Ansible Playbook", "embeds": [{"title": "Ansible Playbook", "description": "Ansible Playbook Agent Fire Execution Successful!","color": 65280}]}'
    "{{ discord_webhook }}"
  ignore_errors: true
  when: ssh_key_result.type == "rsa"

- name: Send Discord Notification on Failure
  command: >
    curl -X POST
    -H "Content-Type: application/json"
    -d '{"content": "Ansible Playbook","embeds": [{"title": "Ansible Playbook", "description": "Ansible Playbook Agent Fire Execution Failed!","color": 16711680}]}'
    "{{ discord_webhook }}"
  ignore_errors: true
  when: ssh_key_result.type != "rsa"