- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Install fontconfig
  ansible.builtin.apt:
    name: fontconfig
    state: present

- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present
  notify: Update apt cache

- name: Display Java version
  ansible.builtin.shell:
    cmd: "java -version"
  register: java_version_output

- name: Print Java version
  ansible.builtin.debug:
    var: java_version_output.stdout_lines

- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
  register: enable_jenkins

- name: Display public key agent fire
  ansible.builtin.debug:
    var: enable_jenkins

- name: Send Discord Notification on Success
  command: >
    curl -X POST
    -H "Content-Type: application/json"
    -d '{"content": "Ansible Playbook Agent Fire Execution Successful!"}'
    "{{ discord_webhook }}"
  ignore_errors: true
  when: enable_jenkins.enabled == true

- name: Send Discord Notification on Failure
  command: >
    curl -X POST
    -H "Content-Type: application/json"
    -d '{"content": "Ansible Playbook Agent Fire Execution Failed!\nError Message: {{ ansible_job_result.msg }}" }'
    "{{ discord_webhook }}"
  ignore_errors: true
  when: enable_jenkins.enabled != false
